version: '3'

services:
  apache:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      volumes:
        - "./:/var/www/html"
      working_dir: /var/www/html
      ports:
        - "8833:80"
  db:
    image: mysql:5.7
    volumes:
      - ./.db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
volumes:
  expertendb:
